### ISSUE TITLE
Why is the nomad server configuration using a temporary folder for data?

### ISSUE THREAD

**Issue by maelp** [picatz/terraform-google-nomad#55]
I see that [this line](https://github.com/picatz/terraform-google-nomad/blob/master/packer/configs/nomad/server.hcl#L3) configures the server to use a temporary path for data, is it intended, or should it also use `/nomad/data`?

Side question: if we run both a binary with the server config and another binary with the client config, on the same server, both pointing to the same data dir, does it cause issues?

**Comment by picatz** [comment]
> I see that [this line](https://github.com/picatz/terraform-google-nomad/blob/master/packer/configs/nomad/server.hcl#L3) configures the server to use a temporary path for data, is it intended, or should it also use /nomad/data?

This is definitely unintended. The [`data_dir`](https://developer.hashicorp.com/nomad/docs/configuration#data_dir) option is used by Nomad server nodes to store cluster state, including the replicated log and snapshot data. This is a great find, and something I plan to fix in the next release of this module.

> Side question: if we run both a binary with the server config and another binary with the client config, on the same server, both pointing to the same data dir, does it cause issues?

Not totally sure, I don't think I've ever done this. From a security perspective, I would advise _against_ doing so. But, I think this would be a good question for [Discuss](https://discuss.hashicorp.com/c/nomad/28).

**Comment by picatz** [comment]
Thank you!
